Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgVMhQdqy_vR_4kp35nBh4K8esAO00ps

**Install dependencies**
"""

get_ipython().system('pip install -q opencv-python-headless matplotlib scikit-learn tensorflow scikit-image gradio Pillow tqdm')

"""**Imports**"""

import os, random, zipfile, warnings
import cv2
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap
from tqdm import tqdm

from skimage.morphology import skeletonize, thin
from skimage.metrics import structural_similarity as ssim
from skimage.feature import local_binary_pattern
from scipy.ndimage import label as scipy_label

from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix, classification_report,
                             roc_curve, auc, precision_recall_curve)

import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import (Conv2D, MaxPooling2D, Flatten, Dense,
                                     Input, Lambda, Dropout, BatchNormalization,
                                     GlobalAveragePooling2D)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow.keras.backend as K

import gradio as gr
from IPython.display import display, HTML

warnings.filterwarnings('ignore')
tf.get_logger().setLevel('ERROR')

print("All libraries loaded.")
print(f"   TensorFlow : {tf.__version__}")
print(f"   OpenCV     : {cv2.__version__}")

import shutil

shutil.rmtree('/content/data', ignore_errors=True)

"""**Upload & extract dataset**"""

from google.colab import files

print("Please upload Dataset.zip ...")
uploaded = files.upload()
zip_path  = list(uploaded.keys())[0]
EXTRACT   = "/content/data"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(EXTRACT)

print("Dataset extracted!")

"""**Detect the dataset root**"""

def find_dataset_root(base):
    """Walk until we find numbered signer folders (e.g. '001', '002')."""
    for root, dirs, _ in os.walk(base):
        dirs_sorted = sorted(dirs)
        numbered = [d for d in dirs_sorted if d.isdigit()]
        if numbered:
            return root
    return base

DATASET_ROOT = find_dataset_root(EXTRACT)
print(f" Dataset root  : {DATASET_ROOT}")

"""**List signer IDs**"""

all_entries = sorted(os.listdir(DATASET_ROOT))
SIGNER_IDS  = sorted({d for d in all_entries
                       if d.isdigit() and (d + "_forg") in all_entries})

print(f"Signers found : {len(SIGNER_IDS)}")

"""**Image-Processing Pipeline**"""

IMG_SIZE = (128, 128)   # width × height fed to CNN

# ── 4-A  Core pre-processor ──────────────────────────────────────────────────
def preprocess_signature(img_bgr, return_steps=False):
    """
    Full image-processing pipeline for one signature image.

    Steps
    -----
    1. Resize to IMG_SIZE
    2. Grayscale conversion
    3. CLAHE  (contrast-limited adaptive histogram equalisation)
    4. Gaussian blur  (noise suppression)
    5. Adaptive thresholding  (local illumination robustness)
    6. Morphological closing  (gap repair)
    7. Largest-contour crop   (remove background / margin noise)
    8. Skeletonisation         (stroke-width normalisation)
    9. Feature extraction: Hu moments + LBP histogram

    Returns
    -------
    skeleton  : (128,128) uint8  –– normalised binary image for CNN
    features  : 1-D float array   –– hand-crafted descriptor
    steps     : dict[str → ndarray]  (only when return_steps=True)
    """
    steps = {}

    # ── 1. Resize ─────────────────────────────────────────────────────────
    img = cv2.resize(img_bgr, IMG_SIZE)
    if return_steps: steps["1 · Original (resized)"] = img.copy()

    # ── 2. Grayscale ──────────────────────────────────────────────────────
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if return_steps: steps["2 · Grayscale"] = gray

    # ── 3. CLAHE – contrast enhancement ───────────────────────────────────
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(gray)
    if return_steps: steps["3 · CLAHE enhanced"] = enhanced

    # ── 4. Gaussian blur ──────────────────────────────────────────────────
    blur = cv2.GaussianBlur(enhanced, (5, 5), 0)
    if return_steps: steps["4 · Gaussian blur"] = blur

    # ── 5. Adaptive threshold (ink → white, background → black) ───────────
    thresh = cv2.adaptiveThreshold(
        blur, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        blockSize=11, C=2
    )
    if return_steps: steps["5 · Adaptive threshold"] = thresh

    # ── 6. Morphological closing  (bridge small gaps in ink strokes) ───────
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    morph  = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)
    if return_steps: steps["6 · Morphological closing"] = morph

    # ── 7. Largest-contour crop  (eliminate stray noise blobs) ────────────
    contours, _ = cv2.findContours(morph, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    clean = np.zeros_like(morph)
    if contours:
        # keep only contours > 0.5 % of image area
        min_area = 0.005 * IMG_SIZE[0] * IMG_SIZE[1]
        for c in contours:
            if cv2.contourArea(c) >= min_area:
                cv2.drawContours(clean, [c], -1, 255, thickness=cv2.FILLED)
    if return_steps: steps["7 · Noise removal"] = clean

    # ── 8. Skeletonisation  (reduce to 1-pixel-wide strokes) ──────────────
    skel_bool = skeletonize(clean // 255)
    skeleton  = (skel_bool * 255).astype(np.uint8)
    if return_steps: steps["8 · Skeleton"] = skeleton

    # ── 9. Feature extraction ─────────────────────────────────────────────
    # 9-a  Hu moments (shape invariants)
    moments = cv2.moments(skeleton)
    hu      = cv2.HuMoments(moments).flatten()
    hu_log  = -np.sign(hu) * np.log10(np.abs(hu) + 1e-10)

    # 9-b  LBP texture histogram (uniform, radius=1, 8 neighbours)
    lbp      = local_binary_pattern(skeleton, P=8, R=1, method='uniform')
    lbp_hist, _ = np.histogram(lbp.ravel(), bins=10, range=(0, 10),
                                density=True)

    # 9-c  Stroke density  (fraction of white pixels)
    density = np.sum(skeleton > 0) / skeleton.size

    features = np.concatenate([hu_log, lbp_hist, [density]])   # (18,)

    if return_steps:
        return skeleton, features, steps
    return skeleton, features


# ── 4-B  Quick visual check ──────────────────────────────────────────────────
def show_pipeline(img_bgr, title="Pipeline Demo"):
    _, _, steps = preprocess_signature(img_bgr, return_steps=True)
    n = len(steps)
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    fig.patch.set_facecolor('#0d0d1a')
    axes = axes.ravel()

    cmap_map = {
        "1 · Original (resized)": None,   # colour
    }
    for ax, (name, img) in zip(axes, steps.items()):
        ax.set_facecolor('#0d0d1a')
        if img.ndim == 3:
            ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        else:
            cmap = 'magma' if 'Skeleton' in name else 'gray'
            ax.imshow(img, cmap=cmap)
        ax.set_title(name, color='white', fontsize=9, pad=4)
        ax.axis('off')

    # hide unused axes
    for ax in axes[n:]:
        ax.set_visible(False)

    plt.suptitle(title, color='#a78bfa', fontsize=14, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.show()

print("Image processing pipeline defined.")

"""**Demo: show pipeline on a real image**"""

demo_folder = os.path.join(DATASET_ROOT, SIGNER_IDS[0])
demo_file   = [f for f in os.listdir(demo_folder)
               if f.lower().endswith(('.jpg','.jpeg','.png'))][0]
demo_img    = cv2.imread(os.path.join(demo_folder, demo_file))

show_pipeline(demo_img, title=f"Preprocessing Pipeline  ·  Signer {SIGNER_IDS[0]}")

"""**Load dataset & build pairs**"""

MAX_SIGNERS = None

def load_signer(signer_id):
    """Return list of (skeleton, features) for one signer."""
    folder = os.path.join(DATASET_ROOT, signer_id)
    items  = []
    for fname in sorted(os.listdir(folder)):
        if not fname.lower().endswith(('.jpg','.jpeg','.png')):
            continue
        img = cv2.imread(os.path.join(folder, fname))
        if img is None:
            continue
        sk, feat = preprocess_signature(img)
        items.append((sk, feat))
    return items


def build_dataset(signer_ids, max_pairs_per_signer=10):
    """
    Pair strategy
    ─────────────
    Genuine  (label=1) : two different genuine signatures of the same person
    Forgery  (label=0) : one genuine + one forged of the same person
    """
    X1, X2, labels = [], [], []

    ids = signer_ids if MAX_SIGNERS is None else signer_ids[:MAX_SIGNERS]

    for sid in tqdm(ids, desc="Loading signers"):
        forg_id  = sid + "_forg"
        genuine  = load_signer(sid)
        forgery  = load_signer(forg_id)

        if len(genuine) < 2 or len(forgery) < 1:
            continue

        # ── Positive pairs: shuffle & zip genuine with itself ──────────────
        g_shuffled = genuine[:]
        random.shuffle(g_shuffled)
        pos_limit = min(max_pairs_per_signer, len(genuine) // 2)
        for i in range(pos_limit):
            X1.append(genuine[i][0])
            X2.append(genuine[i + pos_limit][0])
            labels.append(1)

        # ── Negative pairs: genuine vs forged ─────────────────────────────
        neg_limit = min(max_pairs_per_signer, len(genuine), len(forgery))
        fake_idx  = list(range(len(forgery)))
        random.shuffle(fake_idx)
        for i in range(neg_limit):
            X1.append(genuine[i][0])
            X2.append(forgery[fake_idx[i]][0])
            labels.append(0)

    X1 = np.array(X1, dtype=np.float32)[..., np.newaxis] / 255.0
    X2 = np.array(X2, dtype=np.float32)[..., np.newaxis] / 255.0
    labels = np.array(labels, dtype=np.float32)
    return X1, X2, labels


random.seed(42)
np.random.seed(42)

print("Building dataset pairs …")
X1, X2, labels = build_dataset(SIGNER_IDS)

print(f"\n Pairs built:")
print(f"   Total : {len(labels)}")
print(f"   Genuine  (1) : {labels.sum():.0f}")
print(f"   Forgery  (0) : {(1-labels).sum():.0f}")

(X1_train, X1_test,
 X2_train, X2_test,
 y_train,  y_test) = train_test_split(X1, X2, labels,
                                       test_size=0.20,
                                       stratify=labels,
                                       random_state=42)

print(f"\n   Train : {len(y_train)}   Test : {len(y_test)}")

"""**Siamese CNN model**"""

def build_encoder(input_shape=(128, 128, 1), embedding_dim=128):
    """
    Shared CNN encoder  –  takes a single signature image → embedding vector.

    Architecture
    ────────────
    Block 1 : Conv(32) → BN → ReLU → Conv(32) → BN → ReLU → MaxPool → Dropout
    Block 2 : Conv(64) → BN → ReLU → Conv(64) → BN → ReLU → MaxPool → Dropout
    Block 3 : Conv(128)→ BN → ReLU → GlobalAvgPool
    Head    : Dense(256) → Dense(embedding_dim)
    """
    inp = Input(shape=input_shape, name="img_input")
    x   = inp

    # Block 1
    x = Conv2D(32, (3,3), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = Conv2D(32, (3,3), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D()(x)
    x = Dropout(0.25)(x)

    # Block 2
    x = Conv2D(64, (3,3), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = Conv2D(64, (3,3), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D()(x)
    x = Dropout(0.25)(x)

    # Block 3
    x = Conv2D(128, (3,3), padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = GlobalAveragePooling2D()(x)

    # Embedding head
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.4)(x)
    embedding = Dense(embedding_dim, activation='relu', name="embedding")(x)

    return Model(inp, embedding, name="encoder")


def euclidean_distance(vects):
    """L2 distance between two embedding vectors."""
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True) + K.epsilon())


def contrastive_loss(y_true, y_pred, margin=1.0):
    """
    Contrastive loss  (LeCun et al.)
    Pulls genuine pairs together, pushes forgery pairs apart.
    y_true = 1  →  genuine   →  minimise distance
    y_true = 0  →  forgery   →  maximise distance (up to margin)
    """
    sq_dist   = K.square(y_pred)
    margin_sq = K.square(K.maximum(margin - y_pred, 0))
    return K.mean(y_true * sq_dist + (1 - y_true) * margin_sq)


# ── Build the Siamese graph ───────────────────────────────────────────────────
encoder = build_encoder()
encoder.summary()

input_a = Input(shape=(128, 128, 1), name="inputA")
input_b = Input(shape=(128, 128, 1), name="inputB")

emb_a = encoder(input_a)
emb_b = encoder(input_b)

distance_out = Lambda(euclidean_distance,
                      name="euclidean_dist")([emb_a, emb_b])

siamese_model = Model([input_a, input_b], distance_out,
                       name="Siamese_Network")

siamese_model.compile(
    loss=contrastive_loss,
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3)
)

siamese_model.summary()

"""**Training**"""

callbacks = [
    EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2)
]

history = siamese_model.fit(
    [X1_train, X2_train], y_train,
    validation_data=([X1_test[:300], X2_test[:300]], y_test[:300]),
    epochs=12,
    batch_size=64,
    steps_per_epoch=25,
    validation_steps=8,
    callbacks=callbacks,
    verbose=1
)

print("Training complete.")

pred = siamese_model.predict([X1_test[:5], X2_test[:5]])
print(pred)

"""**Training curves**"""

def plot_training_history(history):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.patch.set_facecolor('#0d0d1a')

    palette = {'train': '#a78bfa', 'val': '#34d399'}

    for ax in axes:
        ax.set_facecolor('#1a1a2e')
        ax.tick_params(colors='white')
        ax.xaxis.label.set_color('white')
        ax.yaxis.label.set_color('white')
        for spine in ax.spines.values():
            spine.set_edgecolor('#333')

    # Loss
    axes[0].plot(history.history['loss'],     color=palette['train'],
                 linewidth=2, label='Train loss')
    axes[0].plot(history.history['val_loss'], color=palette['val'],
                 linewidth=2, linestyle='--', label='Val loss')
    axes[0].set_title('Contrastive Loss', color='white', fontsize=13)
    axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')
    axes[0].legend(facecolor='#1a1a2e', labelcolor='white')
    axes[0].grid(alpha=0.2)

    # Loss diff (overfitting gauge)
    diff = np.array(history.history['val_loss']) - np.array(history.history['loss'])
    axes[1].fill_between(range(len(diff)), diff, alpha=0.4,
                         color='#f97316', label='Val − Train gap')
    axes[1].axhline(0, color='white', linewidth=0.8, linestyle='--')
    axes[1].set_title('Generalisation Gap', color='white', fontsize=13)
    axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Δ Loss')
    axes[1].legend(facecolor='#1a1a2e', labelcolor='white')
    axes[1].grid(alpha=0.2)

    plt.suptitle('Siamese Network Training', color='#a78bfa',
                 fontsize=15, fontweight='bold')
    plt.tight_layout()
    plt.show()


plot_training_history(history)

"""**Threshold calibration  (find optimal decision boundary)**"""

dist_pred = siamese_model.predict([X1_test, X2_test], verbose=0).ravel()

# Genuine → small distance;  Forgery → large distance
# y_test = 1 → genuine → low dist.  Convert to "similarity" for ROC.
similarity = 1 / (1 + dist_pred)   # maps [0, ∞) → (0, 1]

fpr, tpr, thresholds = roc_curve(y_test, similarity)
roc_auc = auc(fpr, tpr)

# Youden's J  –– maximise TPR − FPR
J       = tpr - fpr
best_idx      = np.argmax(J)
best_sim_thr  = thresholds[best_idx]
THRESHOLD     = best_sim_thr          # global threshold used at inference

print(f"  ROC AUC          : {roc_auc:.4f}")
print(f"   Optimal similarity threshold : {THRESHOLD:.4f}")

# ── ROC + PR curves ───────────────────────────────────────────────────────────
precision, recall, _ = precision_recall_curve(y_test, similarity)
pr_auc = auc(recall, precision)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('#0d0d1a')

for ax in axes:
    ax.set_facecolor('#1a1a2e')
    ax.tick_params(colors='white')
    for spine in ax.spines.values():
        spine.set_edgecolor('#333')

# ROC
axes[0].plot(fpr, tpr, color='#a78bfa', linewidth=2.5,
             label=f'ROC  AUC = {roc_auc:.4f}')
axes[0].plot([0,1],[0,1], '--', color='gray', linewidth=1)
axes[0].scatter(fpr[best_idx], tpr[best_idx], color='#f97316',
                zorder=5, s=80, label='Optimal threshold')
axes[0].set_xlabel('False Positive Rate', color='white')
axes[0].set_ylabel('True Positive Rate',  color='white')
axes[0].set_title('ROC Curve', color='white', fontsize=13)
axes[0].legend(facecolor='#1a1a2e', labelcolor='white')
axes[0].grid(alpha=0.2)

# PR
axes[1].plot(recall, precision, color='#34d399', linewidth=2.5,
             label=f'PR  AUC = {pr_auc:.4f}')
axes[1].set_xlabel('Recall',    color='white')
axes[1].set_ylabel('Precision', color='white')
axes[1].set_title('Precision–Recall Curve', color='white', fontsize=13)
axes[1].legend(facecolor='#1a1a2e', labelcolor='white')
axes[1].grid(alpha=0.2)

plt.suptitle('Model Evaluation Curves', color='#a78bfa',
             fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Confusion Matrix**"""

y_pred_bin = (similarity >= THRESHOLD).astype(int)

cm = confusion_matrix(y_test, y_pred_bin)
tn, fp, fn, tp = cm.ravel()

# Custom gradient colormap  (deep purple → electric indigo → neon teal)
cmap_confusion = LinearSegmentedColormap.from_list(
    "sig_cmap",
    ["#0d0d1a", "#4c1d95", "#7c3aed", "#a78bfa", "#34d399"],
    N=256
)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.patch.set_facecolor('#0d0d1a')

# ── Left: styled confusion matrix heatmap ─────────────────────────────────
ax = axes[0]
ax.set_facecolor('#0d0d1a')

im = ax.imshow(cm, cmap=cmap_confusion, aspect='auto',
               vmin=0, vmax=cm.max())

# Colour bar
cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
cbar.ax.yaxis.set_tick_params(color='white')
plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')

# Cell annotations
for i in range(2):
    for j in range(2):
        val   = cm[i, j]
        total = cm[i].sum()
        pct   = 100 * val / total if total else 0
        ax.text(j, i, f"{val}\n({pct:.1f}%)",
                ha='center', va='center',
                color='white', fontsize=14, fontweight='bold')

ax.set_xticks([0, 1])
ax.set_yticks([0, 1])
ax.set_xticklabels(['Predicted\nForgery', 'Predicted\nGenuine'],
                    color='white', fontsize=11)
ax.set_yticklabels(['Actual\nForgery', 'Actual\nGenuine'],
                    color='white', fontsize=11)
ax.set_title('Confusion Matrix', color='#a78bfa',
             fontsize=14, fontweight='bold', pad=15)

# ── Right: per-class metric bars ───────────────────────────────────────────
ax2 = axes[1]
ax2.set_facecolor('#1a1a2e')
for spine in ax2.spines.values():
    spine.set_edgecolor('#333')
ax2.tick_params(colors='white')

accuracy    = (tp + tn) / (tp + tn + fp + fn)
precision_s = tp / (tp + fp + 1e-9)
recall_s    = tp / (tp + fn + 1e-9)
f1          = 2 * precision_s * recall_s / (precision_s + recall_s + 1e-9)
specificity = tn / (tn + fp + 1e-9)
far         = fp / (fp + tn + 1e-9)   # False Acceptance Rate
frr         = fn / (fn + tp + 1e-9)   # False Rejection Rate

metrics  = ['Accuracy', 'Precision', 'Recall\n(Sensitivity)',
            'Specificity', 'F1-Score', 'FAR', 'FRR']
values   = [accuracy, precision_s, recall_s, specificity, f1, far, frr]
colors_b = ['#a78bfa','#34d399','#60a5fa','#f59e0b',
            '#ec4899','#f97316','#ef4444']

bars = ax2.barh(metrics, values, color=colors_b, height=0.55)
ax2.set_xlim(0, 1.15)
ax2.axvline(x=0.5, color='white', linewidth=0.7, linestyle='--', alpha=0.5)

for bar, val in zip(bars, values):
    ax2.text(val + 0.02, bar.get_y() + bar.get_height()/2,
             f"{val:.4f}", va='center', color='white', fontsize=11)

ax2.set_yticklabels(metrics, color='white', fontsize=11)
ax2.set_xlabel('Score', color='white')
ax2.set_title('Per-Metric Performance', color='#a78bfa',
              fontsize=14, fontweight='bold')
ax2.grid(axis='x', alpha=0.2)

plt.suptitle('Model Performance Summary', color='#a78bfa',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Print text report
print("\n" + "═"*55)
print("  CLASSIFICATION REPORT")
print("═"*55)
print(classification_report(y_test, y_pred_bin,
                             target_names=['Forgery','Genuine']))
print(f"  ROC-AUC  : {roc_auc:.4f}")
print(f"  PR-AUC   : {pr_auc:.4f}")
print(f"  FAR      : {far:.4f}   (False Acceptance Rate)")
print(f"  FRR      : {frr:.4f}   (False Rejection Rate)")
print("═"*55)

"""**Inference helper + SSIM & Hu-moment analysis**"""

def verify(img1_bgr, img2_bgr):

    sk1, feat1, steps1 = preprocess_signature(img1_bgr, return_steps=True)
    sk2, feat2, steps2 = preprocess_signature(img2_bgr, return_steps=True)

    # CNN distance
    t1 = sk1.reshape(1, 128, 128, 1).astype(np.float32) / 255.0
    t2 = sk2.reshape(1, 128, 128, 1).astype(np.float32) / 255.0
    dist = siamese_model.predict([t1, t2], verbose=0)[0][0]

    similarity_score = float(1 / (1 + dist))

    # SSIM
    ssim_score, _ = ssim(sk1, sk2, full=True)

    # Hu moments
    hu_dist = float(np.linalg.norm(feat1[:7] - feat2[:7]))

    # LBP similarity
    lbp1 = feat1[7:17]
    lbp2 = feat2[7:17]
    lbp1 = lbp1 / (lbp1.sum() + 1e-9)
    lbp2 = lbp2 / (lbp2.sum() + 1e-9)
    bhatt_coeff = float(np.sum(np.sqrt(lbp1 * lbp2)))

    hu_score = np.exp(-hu_dist)   # converts distance → similarity

    combined = (0.4 * similarity_score +
            0.25 * ssim_score +
            0.25 * bhatt_coeff +
            0.1 * hu_score)

    threshold = 0.75

    verdict = "GENUINE" if combined >= threshold else "FORGERY"

    result = {
        "verdict": verdict,
        "cnn_similarity": similarity_score,
        "ssim": ssim_score,
        "hu_distance": hu_dist,
        "lbp_bhattacharyya": bhatt_coeff,
        "combined_score": combined,
        "threshold_used": threshold,
    }

    return result, steps1, steps2

"""**Gradio Application (UI)**"""

import gradio as gr
import cv2
import numpy as np

def simple_verify(ref_img, test_img):
    try:
        if ref_img is None or test_img is None:
            return "Please upload both images"

        ref_img = (ref_img * 255).astype("uint8") if ref_img.dtype != np.uint8 else ref_img
        test_img = (test_img * 255).astype("uint8") if test_img.dtype != np.uint8 else test_img

        # Convert RGB → BGR
        ref_bgr = cv2.cvtColor(ref_img, cv2.COLOR_RGB2BGR)
        test_bgr = cv2.cvtColor(test_img, cv2.COLOR_RGB2BGR)

        # Run verification
        result, _, _ = verify(ref_bgr, test_bgr)

        # Extract values
        verdict = result.get("verdict", "UNKNOWN")
        combined_score = result.get("combined_score", 0)
        threshold = result.get("threshold_used", 0)

        cnn_score = result.get("cnn_similarity", 0)
        ssim_score = result.get("ssim", 0)

        return f"""
🔍 VERDICT: {verdict}

Combined Score: {combined_score:.4f}
Decision Threshold: {threshold:.4f}

--- Details ---
CNN Similarity: {cnn_score:.4f}
SSIM Score: {ssim_score:.4f}
"""

    except Exception as e:
        print("ERROR:", e)
        return f"Error: {str(e)}"


gr.close_all()

with gr.Blocks() as demo:
    gr.Markdown("# Signature Verification System")

    with gr.Row():
        ref_img = gr.Image(label="Reference Signature (Genuine)", type="numpy")
        test_img = gr.Image(label="Test Signature (Unknown)", type="numpy")

    verify_btn = gr.Button("Verify Signature")

    output = gr.Textbox(label="Result", lines=10)

    verify_btn.click(
        fn=simple_verify,
        inputs=[ref_img, test_img],
        outputs=output
    )

demo.launch(share=True, debug=True)
